/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: D.U. (https://sketchfab.com/DU1701)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-sig-mcx-spear-assaulter-81cc4beeaa9342bebd3bea7dff8f79f2
Title: low-poly SIG MCX Spear Assaulter
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function WeaponModel(props) {
  const { nodes, materials } = useGLTF('/weapon.glb');
  return (
    <group {...props} dispose={null}>
      <group position={[1.529, -0.228, 0]} rotation={[Math.PI, 0, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.brass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.aluminium}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.copper}
        />
      </group>
      <group position={[1.758, -0.949, 0]} rotation={[0, 0, Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.aluminium}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.brass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.copper}
        />
      </group>
      <group position={[0.158, -0.675, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.aluminium}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.anodised_aluminium}
        />
      </group>
      <group position={[-2.074, 0.232, -0.19]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_33.geometry}
          material={materials.anodised_aluminium}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials.cerakote_coyote_tan}
        />
      </group>
      <group position={[-2.625, 0.396, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_38.geometry}
          material={materials.coyote_brown_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials.anodised_aluminium}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_40.geometry}
          material={materials.resin}
        />
      </group>
      <group position={[-0.051, 0.292, -0.204]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials.coyote_brown_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials.anodised_aluminium}
        />
      </group>
      <group position={[0.417, 0.292, -0.214]} scale={[0.023, 0.095, 0.023]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials.anodised_aluminium}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_55.geometry}
          material={materials.cerakote_coyote_tan}
        />
      </group>
      <group position={[0.644, 0.978, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials.nylon}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials.anodised_aluminium}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_59.geometry}
          material={materials.point_emission}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_60.geometry}
          material={materials.glass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.anodised_aluminium}
        position={[0.092, 0.246, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.anodised_aluminium}
        position={[0.103, 0.183, 0.186]}
        rotation={[3.102, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.coyote_brown_2}
        position={[-0.765, 0.629, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.anodised_aluminium}
        position={[-1, -0.149, 0]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.anodised_aluminium}
        position={[-0.69, -0.213, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials.anodised_aluminium}
        position={[-0.201, -0.23, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials.anodised_aluminium}
        position={[-0.336, -0.002, -0.178]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.anodised_aluminium}
        position={[-0.4, -0.009, 0.148]}
        scale={[0.02, 0.014, 0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.anodised_aluminium}
        position={[-2.028, 0.274, -0.047]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.coyote_tan}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_43.geometry}
        material={materials.anodised_aluminium}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.cerakote_coyote_tan}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_45.geometry}
        material={materials.nylon}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.aluminium}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.coyote_brown_2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.coyote_brown_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49.geometry}
        material={materials.coyote_brown_1_bump}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials.aluminium}
        position={[3.562, 0.246, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.124, 0.069, 0.124]}
      />
    </group>
  )
}

useGLTF.preload('/weapon.glb')
