/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 会飞的购物清单 (https://sketchfab.com/flyinglist1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ak15-c288c648239e4156a3e325c2679c3700
Title: AK15
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WeaponModel(props) {
  const { nodes, materials } = useGLTF('/weapon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0'].geometry}
        material={materials.AK15}
        position={[0, 0.456, 0.38]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15���������_AK15���������_0'].geometry}
        material={materials.AK15_1}
        position={[0, 0.829, -1.399]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0_1'].geometry}
        material={materials.AK15_0}
        position={[0, 0.486, 0.628]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0_2'].geometry}
        material={materials.AK15_1}
        position={[0, 0.093, -1.924]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0_3'].geometry}
        material={materials.AK15_2}
        position={[0, 0.285, 1.898]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������������_AK15������������_0'].geometry}
        material={materials.AK15_5}
        position={[0, 1.092, 0.448]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15���������_AK15���������_0_1'].geometry}
        material={materials.AK15_0_6}
        position={[0, 0.097, -1.075]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15���������������_AK15���������������_0'].geometry}
        material={materials.AK15_7}
        position={[0, 0.001, -0.969]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������������_AK15������������_0_1'].geometry}
        material={materials.AK15_0_8}
        position={[0, -0.186, -2.001]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0_4'].geometry}
        material={materials.AK15_3}
        position={[0, 0.576, 3.057]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15���������_AK15���������_0_2'].geometry}
        material={materials.AK15_1_10}
        position={[0, 0.58, 5.084]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15���������_AK15���������_0_3'].geometry}
        material={materials.AK15_2_11}
        position={[0, 0.576, 3.634]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0_5'].geometry}
        material={materials.AK15_4}
        position={[0, 1.416, 3.758]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15���������_AK15���������_0_4'].geometry}
        material={materials.AK15_3_13}
        position={[0.219, 0.367, -2.805]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0_6'].geometry}
        material={materials.AK15_5}
        position={[0, 0.348, -3.871]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������������1_AK15������������1_0'].geometry}
        material={materials.AK151}
        position={[0, -0.252, -5.155]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������������2_AK15������������2_0'].geometry}
        material={materials.AK152}
        position={[0, -0.018, -3.352]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������������3_AK15������������3_0'].geometry}
        material={materials.AK153}
        position={[0, -0.403, -3.241]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0_7'].geometry}
        material={materials.AK15_6}
        position={[0, 0.214, -0.502]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������������_AK15������������_0_2'].geometry}
        material={materials.AK15_1_19}
        position={[0, -0.284, -0.075]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0_8'].geometry}
        material={materials.AK15_7}
        position={[-0.273, 0.466, -1.907]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15���������_AK15���������_0_5'].geometry}
        material={materials.AK15_4_21}
        position={[-0.151, 0.784, -0.344]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������������_AK15������������_0_3'].geometry}
        material={materials.AK15_2_22}
        position={[0, 1.104, -2.111]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������_AK15������_0_9'].geometry}
        material={materials.AK15_8}
        position={[0, 1.245, -2.364]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15������������_AK15������������_0_4'].geometry}
        material={materials.AK15_3_24}
        position={[-0.003, 0.753, -2.737]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15���������������_AK15���������������_0_1'].geometry}
        material={materials.AK15_0_25}
        position={[0, 0.905, 0.034]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['AK15���������������_AK15���������������_0_2'].geometry}
        material={materials.AK15_1_26}
        position={[-0.195, 1.036, 0.467]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/weapon.glb')
